[project]
name = "database-backup-tool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "textual[syntax]>=8.0.2",
    "textual-dev>=1.8.0",
    "psycopg2>=2.9.11",
    "paramiko>=4.0.0",
    "mysql-connector-python>=9.6.0",
    "pymongo>=4.16.0",
    "schedule>=1.2.2",
    "boto3>=1.42.64",
    "google-cloud-storage>=3.9.0",
    "azure-storage-blob>=12.28.0",
    "requests>=2.32.5",
]
